[package]
name = "msm"
version = "0.1.0"
description = "Multiseat VNC remote monitor and control"
authors = ["psychrabi"]
edition.workspace = true
rust-version.workspace = true

[lib]
name = "msm_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
tauri-plugin-os = "2"
tauri-plugin-process = "2"
tauri-plugin-websocket = "2"
keyring = { version = "3", features = ["windows-native"] }
arboard = "3.6.1"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
