use std::{collections::HashSet, net::TcpStream, thread, time::{Duration, Instant}};
use tracing::{info, warn};
use crate::{AppState, FIRST_VNC_PORT, MAX_VNC_PORT, RemoteSession, spawn_worker, terminate_worker};
const WATCHDOG_INTERVAL: Duration = Duration::from_secs(3);
const WORKER_READY_TIMEOUT: Duration = Duration::from_secs(5);
const WORKER_READY_POLL: Duration = Duration::from_millis(100);
const MAX_RETRY_DELAY: Duration = Duration::from_secs(60);
#[derive(Debug, Clone)]
pub struct SessionInfo { pub session_id: u32, pub username: String }
pub fn start(state: AppState) { thread::Builder::new().name("msm-worker-watchdog".to_owned()).spawn(move||run_watchdog(state)).expect("failed to start MSM worker watchdog"); }
fn run_watchdog(state: AppState){info!("MSM worker watchdog started");loop{reconcile(&state);thread::sleep(WATCHDOG_INTERVAL)}}
fn retry_allowed(state:&AppState,session_id:u32)->bool{let failures=state.worker_failures.blocking_lock();let Some((count,at))=failures.get(&session_id) else{return true};let delay=Duration::from_secs(3u64.saturating_mul(1u64<<(count.saturating_sub(1).min(4))));at.elapsed()>=delay.min(MAX_RETRY_DELAY)}
fn record_failure(state:&AppState,session_id:u32){let mut failures=state.worker_failures.blocking_lock();let entry=failures.entry(session_id).or_insert((0,Instant::now()));entry.0=entry.0.saturating_add(1);entry.1=Instant::now();warn!(session_id,attempt=entry.0,"worker start failure recorded; retry backoff active")}
fn clear_failure(state:&AppState,session_id:u32){state.worker_failures.blocking_lock().remove(&session_id)}
fn reconcile(state:&AppState){let sessions=match enumerate_windows_sessions(){Ok(s)=>s,Err(e)=>{warn!(%e,"failed to enumerate Windows sessions; preserving workers");return}};let active_sessions:HashSet<u32>=sessions.iter().map(|s|s.session_id).collect();{let mut workers=state.workers.blocking_lock();workers.retain(|session_id,worker|{if is_process_alive(worker.worker_pid){true}else{warn!(session_id,worker_pid=worker.worker_pid,"worker exited; it will be respawned");false}})}
{let mut workers=state.workers.blocking_lock();let stale:Vec<(u32,u32)>=workers.iter().filter_map(|(id,w)|(!active_sessions.contains(id)).then_some((*id,w.worker_pid))).collect();for(id,pid)in stale{info!(session_id=id,worker_pid=pid,"interactive session ended; stopping worker");terminate_worker(pid);workers.remove(&id);clear_failure(state,id)}}
for session in sessions{let worker_alive={let workers=state.workers.blocking_lock();workers.get(&session.session_id).is_some_and(|w|is_process_alive(w.worker_pid))};if worker_alive{clear_failure(state,session.session_id);continue}if !retry_allowed(state,session.session_id){continue}match spawn_worker_for_session(state,&session){Ok(_)=>clear_failure(state,session.session_id),Err(e)=>{record_failure(state,session.session_id);warn!(session_id=session.session_id,username=%session.username,%e,"failed to start worker; watchdog will retry")}}}}
fn spawn_worker_for_session(state:&AppState,session:&SessionInfo)->Result<RemoteSession,Box<dyn std::error::Error+Send+Sync>>{let _lifecycle_lock=state.worker_operations.blocking_lock();if let Some(existing)=state.workers.blocking_lock().get(&session.session_id).cloned(){if is_process_alive(existing.worker_pid){return Ok(existing)}terminate_worker(existing.worker_pid);state.workers.blocking_lock().remove(&session.session_id)}let port={let workers=state.workers.blocking_lock();allocate_worker_port(&workers)}.ok_or_else(||"no available VNC worker ports".to_owned())?;let password=uuid::Uuid::new_v4().simple().to_string();let worker_pid=spawn_worker(session.session_id,port,&password)?;info!(session_id=session.session_id,username=%session.username,worker_pid,port,"spawned session worker");if !wait_for_worker_ready(worker_pid,port){terminate_worker(worker_pid);return Err(format!("worker PID {worker_pid} did not become ready on port {port}").into())}let remote_session=RemoteSession{session_id:session.session_id.to_string(),port,vnc_password:password,vnc_ticket:String::new(),worker_pid};state.workers.blocking_lock().insert(session.session_id,remote_session.clone());Ok(remote_session)}
fn wait_for_worker_ready(pid:u32,port:u16)->bool{let deadline=Instant::now()+WORKER_READY_TIMEOUT;let address=match format!("127.0.0.1:{port}").parse(){Ok(a)=>a,Err(_)=>return false};while Instant::now()<deadline{if !is_process_alive(pid){return false}if TcpStream::connect_timeout(&address,WORKER_READY_POLL).is_ok(){return true}thread::sleep(WORKER_READY_POLL)}false}
fn allocate_worker_port(workers:&std::collections::HashMap<u32,RemoteSession>)->Option<u16>{(FIRST_VNC_PORT..=MAX_VNC_PORT).find(|port|workers.values().all(|worker|worker.port!=*port))}
pub async fn ensure_session(state:&AppState,session_id:u32)->Result<RemoteSession,Box<dyn std::error::Error+Send+Sync>>{let state=state.clone();tokio::task::spawn_blocking(move||{let session=enumerate_windows_sessions()?.into_iter().find(|s|s.session_id==session_id).ok_or_else(||format!("session {session_id} is not active"))?;spawn_worker_for_session(&state,&session)}).await.map_err(|e|Box::new(e)as Box<dyn std::error::Error+Send+Sync>)?}
fn enumerate_windows_sessions()->Result<Vec<SessionInfo>,Box<dyn std::error::Error+Send+Sync>>{#[cfg(windows)]{use windows::Win32::System::RemoteDesktop::{WTS_CURRENT_SERVER_HANDLE,WTS_SESSION_INFOW,WTSEnumerateSessionsW,WTSFreeMemory,WTSQuerySessionInformationW,WTSUserName};use windows::core::PWSTR;unsafe{let mut p:*mut WTS_SESSION_INFOW=std::ptr::null_mut();let mut count=0u32;WTSEnumerateSessionsW(Some(WTS_CURRENT_SERVER_HANDLE),0,1,&mut p,&mut count)?;if p.is_null(){return Ok(Vec::new())}let sessions=std::slice::from_raw_parts(p,count as usize);let mut result=Vec::new();for session in sessions{if session.SessionId==0{continue}let mut up=PWSTR(std::ptr::null_mut());let mut bytes=0u32;if WTSQuerySessionInformationW(Some(WTS_CURRENT_SERVER_HANDLE),session.SessionId,WTSUserName,&mut up,&mut bytes).is_err()||up.is_null(){continue}let chars=std::slice::from_raw_parts(up.as_ptr(),(bytes as usize/2).saturating_sub(1));let username=String::from_utf16_lossy(chars);WTSFreeMemory(up.as_ptr() as _);if username.trim().is_empty()||username.eq_ignore_ascii_case("system"){continue}info!(session_id=session.SessionId,username=%username,"discovered interactive session");result.push(SessionInfo{session_id:session.SessionId,username})}WTSFreeMemory(p as _);Ok(result)}}#[cfg(not(windows))]{Ok(Vec::new())}}
fn is_process_alive(pid:u32)->bool{#[cfg(windows)]{use windows::Win32::Foundation::CloseHandle;use windows::Win32::System::Threading::{GetExitCodeProcess,OpenProcess,PROCESS_QUERY_LIMITED_INFORMATION};const STILL_ACTIVE:u32=259;unsafe{let process=match OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,false,pid){Ok(p)=>p,Err(_)=>return false};let mut exit_code=0u32;let alive=GetExitCodeProcess(process,&mut exit_code).is_ok()&&exit_code==STILL_ACTIVE;let _=CloseHandle(process);alive}}#[cfg(not(windows))]{let _=pid;true}}
